### ISSUE TITLE
Request : add more information 

### ISSUE THREAD

**Issue by Chamiu** [smittytone/PreviewMarkdown#1]
I think that adding a background icon that indicates the Markdown format will further improve visibility, but what about?

**Comment by smittytone** [comment]
I'm not sure what you mean by this. Do you mean an icon that shows what type of Markdown a file contains? if it's just to show that it is a markdown file, that's already clear from the file name displayed at the top of the preview window?

**Comment by Chamiu** [comment]
> I'm not sure what you mean by this. Do you mean an icon that shows what type of Markdown a file contains? if it's just to show that it is a markdown file, that's already clear from the file name displayed at the top of the preview window?

Sorry.
This idea mean a file icon at document type icon that overlay preview "ON" on Finder.
Attach file is overlay example.(check mark is Dropbox sync)
<img width="121" alt="Markdown Preview Icon" src="https://user-images.githubusercontent.com/2077600/102362955-4b23aa80-3ff8-11eb-82f3-62148407bd2d.png">

**Comment by smittytone** [comment]
I see what you mean now - thanks. I think most people will use the file extension to see what kind of file it is, but this may be worth offering as an option.

**Comment by Chamiu** [comment]
>  I think most people will use the file extension to see what kind of file it is.

I think so me, too.
But macOS and Windows are default OFF at “Show all filename extensions.”
And I think that young people who start using computers from smartphones often do not understand the extension itself, from classic MacOS user too.

Users from DOS must understand the extension itself. it's me.

**Comment by smittytone** [comment]
Working on adding this to the next release.

**Comment by smittytone** [comment]
Released in version 1.2.0
