### ISSUE TITLE
README should include build instructions

### ISSUE THREAD

**Issue by mgrider** [smittytone/PreviewMarkdown#3]
Clearly provisioning needs to change on all the targets, but after that, I still get the following error:

```
error: Build input file cannot be found: '<path snip>/OneDrive/Programming/mnu/Secrets.swift' (in target 'Previewer' from project 'PreviewMarkdown')
```

**Comment by smittytone** [comment]
It does mention this under the Source Code heading.

**Comment by mgrider** [comment]
I mistakenly assumed your goal was to make this usable. Never mind then.
